### ISSUE TITLE
I would like to manage docker outside of this role

### ISSUE THREAD

**Issue by midolo** [digital-realms/ansible_role_kubernetes_master#4]
As an Admin I would like to be able to manage Docker outside of this role. This will give me the independence with regards to what versions I install and what configurations I place on the Docker Engine.

**Comment by stevedotmt** [comment]
Best way to do this is setting a simple variable for example `install_docker` instead of checking manually, for the reasons you brought up, which having 3 different names `docker`, `docker-egine`, `docker-io` will result into a noisy role.
